#!/usr/bin/env php
<?php

declare(strict_types=1);

use Simai\Docara\Console\ApplicationFactory;

$projectAutoload = (getcwd() ?: '.') . '/vendor/autoload.php';
if (is_file($projectAutoload)) {
    require_once $projectAutoload;
}

$packageAutoload = __DIR__ . '/vendor/autoload.php';
if (is_file($packageAutoload)) {
    require_once $packageAutoload;
}

exit(ApplicationFactory::create()->run());
